// Salvage-auction education cluster — damage types and vehicle types drive
// /auctions, /auctions/damage/[type], and /auctions/type/[type]. These are
// EDUCATIONAL pages (what each damage/vehicle category means and what to check),
// funneling to the VIN check — we do NOT list live auction inventory, so there
// is no data feed to fabricate. Same source-of-truth pattern as BRANDS.

export interface AuctionCategory {
  slug: string;
  name: string;
  short: string; // one-line summary
  body: string; // 2-3 sentence educational description
  checks: string[]; // what a buyer should check
}

export const DAMAGE_TYPES: AuctionCategory[] = [
  { slug: 'hail', name: 'Hail damage', short: 'Dents from a hailstorm.', body: 'Hail-damaged vehicles have dents across the hood, roof, and body panels from a hailstorm. The damage is usually cosmetic, but severe hail can crack glass or dent the roof enough to be branded.', checks: ['Whether a hail or salvage brand is on the title', 'Cracked windshield or sunroof glass', 'Roof and panel dent severity'] },
  { slug: 'flood', name: 'Flood damage', short: 'Submerged or water-damaged.', body: 'Flood vehicles were submerged or soaked. Water causes electrical faults, mold, and corrosion that keep surfacing long after a cosmetic clean-up, which makes flood cars uniquely risky.', checks: ['A flood or water-damage title brand', 'Musty smell and hidden moisture', 'Corrosion on connectors and under carpets'] },
  { slug: 'theft', name: 'Theft / recovery', short: 'Reported stolen and recovered.', body: 'These vehicles were reported stolen and later recovered. Recovered cars can be missing parts or hide damage sustained during the theft.', checks: ['Theft records via the VIN', 'Matching VIN plates across the car', 'Missing or replaced components'] },
  { slug: 'burn', name: 'Fire / burn damage', short: 'Burn damage from a fire.', body: 'Fire-damaged vehicles sustained burn damage to the body, interior, or engine bay. Heat and smoke damage to wiring and structure is often unsafe and expensive to repair correctly.', checks: ['Extent of structural and wiring damage', 'A fire or salvage title brand', 'Smoke damage to electronics'] },
  { slug: 'rollover', name: 'Rollover damage', short: 'The vehicle flipped.', body: 'Rollover vehicles flipped onto their side or roof. Roof, pillar, and structural damage from a rollover is serious and directly affects crash safety.', checks: ['Roof and pillar repair quality', 'Airbag deployment and replacement', 'Frame/structural integrity'] },
  { slug: 'front-end', name: 'Front-end damage', short: 'Damage to the front of the car.', body: 'Front-end collisions affect the hood, bumper, radiator, and frequently the frame and airbags. Repair quality on the frame and airbag system is safety-critical.', checks: ['Airbag replacement', 'Frame alignment', 'Radiator and cooling repairs'] },
  { slug: 'rear-end', name: 'Rear-end damage', short: 'Damage to the back of the car.', body: 'Rear-end collisions affect the trunk, rear bumper, and rear structure, and can bend the frame. Confirm the repairs were done properly.', checks: ['Rear frame/unibody repair', 'Trunk and floor alignment', 'Rear safety systems'] },
  { slug: 'side', name: 'Side damage', short: 'Damage to a side of the car.', body: 'Side-impact damage affects doors, pillars, and the side structure, and can involve side airbags. Structural side repairs are among the most safety-critical.', checks: ['Side airbag replacement', 'Door and pillar alignment', 'Structural repair quality'] },
  { slug: 'frame', name: 'Frame damage', short: 'Structural frame damage.', body: 'Frame damage means the vehicle structural frame was bent or compromised. It is among the most serious damage types and is difficult and costly to repair to spec.', checks: ['Professional frame measurement', 'Even panel gaps and tire wear', 'A structural or salvage brand'] },
  { slug: 'engine', name: 'Engine damage', short: 'Engine or powertrain damage.', body: 'Engine-damaged vehicles have a damaged or non-running powertrain. Repair or replacement can easily exceed the car value.', checks: ['Whether the engine runs', 'Cost of repair vs. value', 'Cause of the failure'] },
  { slug: 'transmission', name: 'Transmission damage', short: 'Faulty or failed transmission.', body: 'Transmission-damaged vehicles have a faulty or failed gearbox. A transmission replacement is a major expense to factor into any bid.', checks: ['Shifting behavior', 'Replacement cost', 'Related drivetrain damage'] },
  { slug: 'mechanical', name: 'Mechanical damage', short: 'Drivetrain / component failure.', body: 'Mechanical listings cover drivetrain and component failures that keep the vehicle from running normally, without necessarily any body damage.', checks: ['Which components failed', 'Whether it runs and drives', 'Total repair estimate'] },
  { slug: 'minor-dents', name: 'Minor dents & scratches', short: 'Light cosmetic damage.', body: 'Minor dents and scratches are cosmetic and do not affect safety. They are common on lightly used cars or lot-damaged inventory.', checks: ['Whether damage is purely cosmetic', 'Clean title status', 'Paint match on repairs'] },
  { slug: 'no-damage', name: 'No visible damage', short: 'Often repossessions or returns.', body: 'No-damage listings are often repossessions, lease returns, or dealer overstock rather than wrecked cars. They can be good value, but still need a history check.', checks: ['Title and lien status', 'Odometer history', 'Reason it is at auction'] },
  { slug: 'vandalism', name: 'Vandalism', short: 'Intentional damage.', body: 'Vandalism includes keying, broken glass, and intentional body damage. It is usually cosmetic, but confirm whether it led to a title brand.', checks: ['Extent of cosmetic damage', 'Broken glass or lights', 'Any resulting brand'] },
  { slug: 'repossession', name: 'Repossession', short: 'Taken back by a lender.', body: 'Repossessed vehicles were reclaimed by a lender for missed payments, not necessarily because of damage. Confirm the title is clear and any lien is released.', checks: ['Clear title and released lien', 'Overall condition', 'Odometer and service history'] },
  { slug: 'vin-issue', name: 'VIN issue', short: 'Problem with the VIN.', body: 'A VIN issue flags a missing, altered, or mismatched Vehicle Identification Number. This is a serious red flag and should be treated with extreme caution.', checks: ['Matching VIN plates everywhere', 'Title vs. car VIN', 'Theft and cloning records'] },
  { slug: 'stripped', name: 'Stripped', short: 'Missing major parts.', body: 'Stripped vehicles are missing major components such as wheels, seats, or electronics, often after a theft. Replacement costs add up quickly.', checks: ['Which parts are missing', 'Replacement cost', 'Associated theft record'] },
  { slug: 'biohazard', name: 'Biohazard', short: 'May need professional cleanup.', body: 'Biohazard listings may have contamination requiring professional cleanup. Proceed with caution and insist on full disclosure.', checks: ['Nature of the biohazard', 'Professional remediation', 'Full seller disclosure'] },
  { slug: 'storm', name: 'Storm damage', short: 'Wind, debris, or water damage.', body: 'Storm-damaged vehicles were affected by severe weather — wind, debris, or water — and overlap with hail and flood categories.', checks: ['Whether water intrusion occurred', 'A weather-related title brand', 'Hidden electrical damage'] },
  { slug: 'roof', name: 'Roof damage', short: 'Damage to the roof structure.', body: 'Roof damage affects the top structure, often from a rollover, falling debris, or a crushed roof. These are structural, safety-critical repairs.', checks: ['Roof structural repair', 'Rollover history', 'Water leaks after repair'] },
  { slug: 'interior', name: 'Interior damage', short: 'Damage to seats, dash, trim.', body: 'Interior damage affects seats, the dashboard, and trim, from water, fire, or vandalism. It can also signal a larger underlying problem such as flooding.', checks: ['Cause of the interior damage', 'Signs of water intrusion', 'Electronics function'] },
  { slug: 'windows', name: 'Window / glass damage', short: 'Cracked or broken glass.', body: 'Window damage means cracked or broken glass. It is usually inexpensive to fix, but broken glass can accompany theft or vandalism.', checks: ['Which glass is damaged', 'Signs of forced entry', 'Related theft or vandalism'] },
  { slug: 'all-over', name: 'All-over damage', short: 'Damage across the vehicle.', body: 'All-over listings are damaged across multiple areas, typically a severe wreck or a total loss. These are usually parts or project vehicles.', checks: ['Whether it is a total loss', 'Structural integrity', 'Realistic repair scope'] },
  { slug: 'partial-repair', name: 'Partial repair', short: 'Some damage fixed, not all.', body: 'Partially repaired vehicles had some damage addressed but not all. Verify exactly what was and was not completed, and to what standard.', checks: ['What repairs remain', 'Quality of completed work', 'Documentation of the original damage'] },
];

export const VEHICLE_TYPES: AuctionCategory[] = [
  { slug: 'automobile', name: 'Automobiles', short: 'Cars and passenger vehicles.', body: 'Passenger cars are the most common auction category, ranging from clean repossessions and lease returns to salvage-title wrecks.', checks: ['Title brand and lien status', 'Odometer history', 'Reported accidents'] },
  { slug: 'motorcycle', name: 'Motorcycles', short: 'Two-wheeled motorcycles.', body: 'Motorcycles carry a 17-character VIN (usually on the steering neck) and can have salvage and theft brands just like cars.', checks: ['Frame VIN vs. title', 'Salvage or theft records', 'Engine and frame damage'] },
  { slug: 'truck', name: 'Trucks', short: 'Pickups and commercial trucks.', body: 'Pickups and commercial trucks appear at auction as work vehicles, fleet units, and salvage. Many have heavy use to account for.', checks: ['Frame and bed condition', 'Mileage and service history', 'Any title brand'] },
  { slug: 'boat', name: 'Boats', short: 'Boats and watercraft.', body: 'Boats use a Hull Identification Number (HIN) and can be salvage, storm, or flood damaged. Verify the identification and damage history.', checks: ['HIN and title status', 'Water and impact damage', 'Engine hours and condition'] },
  { slug: 'atv', name: 'ATVs', short: 'All-terrain vehicles.', body: 'ATVs are off-road recreational vehicles. Check the frame and engine, since off-road use can hide structural wear.', checks: ['Frame and suspension damage', 'Engine condition', 'Title and identification'] },
  { slug: 'snowmobile', name: 'Snowmobiles', short: 'Winter recreation vehicles.', body: 'Snowmobiles are winter recreational vehicles. Verify identification and any damage or theft history before bidding.', checks: ['Track and suspension wear', 'Engine condition', 'Identification and title'] },
  { slug: 'jet-ski', name: 'Jet skis', short: 'Personal watercraft.', body: 'Personal watercraft (jet skis) are prone to water intrusion and impact damage. Confirm the identification and inspect for hidden damage.', checks: ['Hull and impact damage', 'Water intrusion signs', 'Engine hours'] },
  { slug: 'trailer', name: 'Trailers', short: 'Utility, cargo, travel trailers.', body: 'Utility, cargo, and travel trailers carry a frame VIN and can be branded salvage or flood. Check the frame and title before buying.', checks: ['Frame VIN and title brand', 'Structural and floor condition', 'Axle and hitch integrity'] },
  { slug: 'motorhome', name: 'Motorhomes', short: 'Motorhomes and RVs.', body: 'Motorhomes combine a chassis and a coach, and both parts can carry damage or a title brand. Inspect and check the history for each.', checks: ['Chassis and coach VINs', 'Water damage and leaks', 'Any salvage or flood brand'] },
  { slug: 'bus', name: 'Buses', short: 'Passenger transport buses.', body: 'Buses and passenger-transport vehicles are often high-mileage fleet units. Service history and mechanical condition matter most.', checks: ['Mileage and maintenance records', 'Mechanical condition', 'Title and fleet history'] },
  { slug: 'heavy-equipment', name: 'Heavy equipment', short: 'Construction machinery.', body: 'Construction and heavy equipment use serial identifiers, and operating hours often matter more than a standard VIN. Inspect for wear and prior repairs.', checks: ['Operating hours', 'Serial/identification match', 'Hydraulic and structural condition'] },
  { slug: 'motorbike', name: 'Motorbikes', short: 'Motorbikes and mopeds.', body: 'Smaller two-wheelers such as motorbikes and mopeds have their own VIN locations and can carry salvage or theft brands.', checks: ['VIN location and match', 'Salvage or theft records', 'Frame and engine condition'] },
];

export function getDamageType(slug: string): AuctionCategory | undefined {
  return DAMAGE_TYPES.find((d) => d.slug === slug);
}

export function getVehicleType(slug: string): AuctionCategory | undefined {
  return VEHICLE_TYPES.find((v) => v.slug === slug);
}
