import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SITE_URL, SITE_NAME, SITE_DESCRIPTION, SITE_TAGLINE } from "@/lib/site";
import { siteGraphLd } from "@/lib/structured-data";
import JsonLd from "@/components/JsonLd";
import AnalyticsTracker from "@/components/AnalyticsTracker";
import GoogleAnalytics from "@/components/GoogleAnalytics";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#2563eb",
  colorScheme: "light",
};

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Distinctive display face for hero headlines (ui-ux-pro-max "Tech Startup"
// pairing). Plus Jakarta Sans stays the body/UI workhorse.
const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — ${SITE_TAGLINE}`,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "VIN check",
    "VIN lookup",
    "vehicle history report",
    "license plate lookup",
    "NMVTIS report",
    "salvage title check",
    "free VIN check",
    "car history report",
    "odometer check",
    "stolen car check",
  ],
  alternates: {
    canonical: "/",
  },
  manifest: "/manifest.webmanifest",
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    url: SITE_URL,
    locale: "en_US",
    // OG/Twitter images are generated by app/opengraph-image.png.tsx (convention).
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "automotive",
};

// Site-wide identity graph (Organization + WebSite + Service). Pricing in the
// Service offer comes from pricing.ts, so it never goes stale. Page-specific
// schema (FAQPage, HowTo, BreadcrumbList) is added by the individual pages.
function StructuredData() {
  return <JsonLd data={siteGraphLd()} />;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-US">
      <body
        className={`${jakarta.variable} ${geistMono.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <StructuredData />
        <GoogleAnalytics />
        <AnalyticsTracker />
        {children}
      </body>
    </html>
  );
}
